In [44]:
import pandas as pd


import numpy as np

df = pd.read_csv("C:\\Users\\HERMAN_NOBLE\\Desktop\\BLOSSOM\\assigngement1\\billboard.csv")
df

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.shape

(317, 81)

In [10]:
df.columns

Index(['artiste', 'track', 'genre', 'date.entered', 'date.peaked', 'x1st.week',
       'x2nd.week', 'x3rd.week', 'x4th.week', 'x5th.week', 'x6th.week',
       'x7th.week', 'x8th.week', 'x9th.week', 'x10th.week', 'x11th.week',
       'x12th.week', 'x13th.week', 'x14th.week', 'x15th.week', 'x16th.week',
       'x17th.week', 'x18th.week', 'x19th.week', 'x20th.week', 'x21st.week',
       'x22nd.week', 'x23rd.week', 'x24th.week', 'x25th.week', 'x26th.week',
       'x27th.week', 'x28th.week', 'x29th.week', 'x30th.week', 'x31st.week',
       'x32nd.week', 'x33rd.week', 'x34th.week', 'x35th.week', 'x36th.week',
       'x37th.week', 'x38th.week', 'x39th.week', 'x40th.week', 'x41st.week',
       'x42nd.week', 'x43rd.week', 'x44th.week', 'x45th.week', 'x46th.week',
       'x47th.week', 'x48th.week', 'x49th.week', 'x50th.week', 'x51st.week',
       'x52nd.week', 'x53rd.week', 'x54th.week', 'x55th.week', 'x56th.week',
       'x57th.week', 'x58th.week', 'x59th.week', 'x60th.week', 'x61st.week',
       'x62nd.week', 'x63rd.week', 'x64th.week', 'x65th.week', 'x66th.week',
       'x67th.week', 'x68th.week', 'x69th.week', 'x70th.week', 'x71st.week',
       'x72nd.week', 'x73rd.week', 'x74th.week', 'x75th.week', 'x76th.week'],
      dtype='object')

In [11]:
df.dtypes

artiste          object
track            object
genre            object
date.entered     object
date.peaked      object
                 ...
x72nd.week      float64
x73rd.week      float64
x74th.week      float64
x75th.week      float64
x76th.week      float64
Length: 81, dtype: object

In [13]:
df['date.entered'] = pd.to_datetime(df['date.entered'])

df.dtypes['date.entered']

dtype('<M8[ns]')

In [14]:
df['date.peaked'] = pd.to_datetime(df['date.peaked'])

df.dtypes

artiste                 object
track                   object
genre                   object
date.entered    datetime64[ns]
date.peaked     datetime64[ns]
                     ...
x72nd.week             float64
x73rd.week             float64
x74th.week             float64
x75th.week             float64
x76th.week             float64
Length: 81, dtype: object

In [15]:
df.columns

Index(['artiste', 'track', 'genre', 'date.entered', 'date.peaked', 'x1st.week',
       'x2nd.week', 'x3rd.week', 'x4th.week', 'x5th.week', 'x6th.week',
       'x7th.week', 'x8th.week', 'x9th.week', 'x10th.week', 'x11th.week',
       'x12th.week', 'x13th.week', 'x14th.week', 'x15th.week', 'x16th.week',
       'x17th.week', 'x18th.week', 'x19th.week', 'x20th.week', 'x21st.week',
       'x22nd.week', 'x23rd.week', 'x24th.week', 'x25th.week', 'x26th.week',
       'x27th.week', 'x28th.week', 'x29th.week', 'x30th.week', 'x31st.week',
       'x32nd.week', 'x33rd.week', 'x34th.week', 'x35th.week', 'x36th.week',
       'x37th.week', 'x38th.week', 'x39th.week', 'x40th.week', 'x41st.week',
       'x42nd.week', 'x43rd.week', 'x44th.week', 'x45th.week', 'x46th.week',
       'x47th.week', 'x48th.week', 'x49th.week', 'x50th.week', 'x51st.week',
       'x52nd.week', 'x53rd.week', 'x54th.week', 'x55th.week', 'x56th.week',
       'x57th.week', 'x58th.week', 'x59th.week', 'x60th.week', 'x61st.week',
       'x62nd.week', 'x63rd.week', 'x64th.week', 'x65th.week', 'x66th.week',
       'x67th.week', 'x68th.week', 'x69th.week', 'x70th.week', 'x71st.week',
       'x72nd.week', 'x73rd.week', 'x74th.week', 'x75th.week', 'x76th.week'],
      dtype='object')

In [49]:
#applying melt to obtain the week and rank column

df_music = pd.melt(df, id_vars=['artiste','track','genre','date.entered', 'date.peaked'], value_name = 'rank', var_name='week')
               

df_music

,artiste,track,genre,date.entered,date.peaked,week,rank
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,x1st.week,78.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,x1st.week,15.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,x1st.week,71.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,x1st.week,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,x1st.week,57.0
...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,x76th.week,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,x76th.week,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,x76th.week,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,x76th.week,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,x76th.week,NaN

In [52]:
#checking for data types
df_music.dtypes

artiste          object
track            object
genre            object
date.entered     object
date.peaked      object
week             object
rank            float64
dtype: object

In [56]:
#changing the datatype for date.entered and date.peaked

df_music['date.entered'] = pd.to_datetime(df_music['date.entered'])


df_music['date.peaked'] = pd.to_datetime(df_music['date.peaked'])


df_music.dtypes

artiste                 object
track                   object
genre                   object
date.entered    datetime64[ns]
date.peaked     datetime64[ns]
week                     int32
rank                   float64
dtype: object

In [58]:
df_music['week'] = df_music['week'].apply(str)

In [59]:
df_music['week'] = df_music['week'].str.extract('(\d+)').astype(int)

df_music

,artiste,track,genre,date.entered,date.peaked,week,rank
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,1,78.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,1,15.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,1,71.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,1,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,1,57.0
...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,76,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,76,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,76,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,76,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,76,NaN

In [60]:
df_music['week'] = df_music['week'].apply(int)

In [61]:
df_music.dtypes

artiste                 object
track                   object
genre                   object
date.entered    datetime64[ns]
date.peaked     datetime64[ns]
week                     int64
rank                   float64
dtype: object

In [54]:
#extracting numbers from the week column
df_music['week'] = df_music['week'].str.extract('(\d+)').astype(int)

df_music

AttributeError: Can only use .str accessor with string values!

KeyError: 'week'